ChangeLog.md, coxeter/shape_classes/__init__.py, doc/requirements.txt, doc/source/coxeter.common_shapes.rst, doc/source/coxeter.rst, doc/source/coxeter.shape_classes.rst, doc/source/credits.rst, doc/source/index.rst, doc/source/modules.rst, readthedocs.yml
Enables RTD support.
Documentation should be hosted publicly online.
=> Enable rtd

ChangeLog.md, coxeter/shape_classes/polyhedron.py, tests/conftest.py, tests/test_polygon.py, tests/test_polyhedron.py, tests/test_spheropolygon.py
Replace random point generation with generation of points on surface of ellipse or ellipsoid to avoid degeneracy.
Resolves #73. It may still be technically possible to generate highly degenerate simplices, but the probability is substantially lower with this method. Increasing the number of points should help if that becomes a problem.
=> Select test points from the surface of a conic section

README.rst
Update readme with better instructions on how to make the docs.
Replaced current instructions to reflect the latest way to create docs
=> [minor] Readme update

doc/source/package-shape-families.rst
Autodoc the call operator for shape families.
The parameters of the call operator are already present in the docstring, but need to be included in the online docs since this is the primary interface to the class.
=> Document the call operator for shape families.

coxeter/shape_classes/convex_spheropolygon.py, tests/test_spheropolygon.py
added radius getter setter tests and check that the radius is positive. 
added radius getter setter tests and check that the radius is positive. 
These getter and setter tests do were not in the code before. 
=> added radius getter setter tests

.circleci/config.yml
This refactors the CI.
- CI will install and run tests from the local wheels before uploading to PyPI.
- Style check requirements and testing syntax have been de-duplicated.
No changelog needed.
=> Refactor CI config.

coxeter/families/common.py
I clarified the formulas for n-gon generation. I found the previous code comments a little confusing, since they looked like dead code instead of a math expression.
=> Clarified n-gon formulas.

coxeter/shapes/circle.py, coxeter/shapes/convex_spheropolygon.py, coxeter/shapes/ellipse.py, coxeter/shapes/ellipsoid.py, coxeter/shapes/polygon.py, coxeter/shapes/polyhedron.py, coxeter/shapes/sphere.py, coxeter/shapes/utils.py
I noticed a few more problems in the docs. This fixes the following:
- More consistent sphinx references.
- Revise Polygon class summary so it renders (instead of being cut off at the period).
- Fix missing types in docstrings, other improvements.
Just fixing the stuff I see while writing code...
=> Documentation revisions

coxeter/shapes/ellipsoid.py
Use the wording of wikipedia at https://en.wikipedia.org/wiki/Ellipsoid#Standard_equation in the documentation
[Hoomd uses the wording "half-axis"](https://hoomd-blue.readthedocs.io/en/latest/module-hpmc-integrate.html#hoomd.hpmc.integrate.Ellipsoid.shape)
[GSD just uses "radius in _ direction"
](https://gsd.readthedocs.io/en/stable/shapes.html#ellipsoids)
=> Use similar wording to gsd and hoomd (half axis)

.gitignore, doc/requirements.txt, doc/source/conf.py
Define the bibtex_bibfiles variable in conf.py
Necessary update for sphinxcontrib-bibtex v2.0
=> Update to use sphinxcontrib-bibtex v2.0.

.circleci/config.yml
=> Add CI tests for Python 3.9.

coxeter/bentley_ottmann/poly_point_isect.py, coxeter/polytri/polytri.py, coxeter/shapes/circle.py, coxeter/shapes/convex_polygon.py, coxeter/shapes/convex_spheropolygon.py, coxeter/shapes/ellipse.py, tests/test_circle.py, tests/test_ellipse.py, tests/test_polygon.py, tests/test_spheropolygon.py
Methods for calculating 2D shape kernels (excluding convex spheropolygons and concave polygons). 
Added shape kernels methods that would take any array of angular values from 0 to 2pi and return the shape kernel at those angular values for the shapes listed. 
Shape kernels are useful for theoretical applications in the lab and serve as another general tool to understand shapes. 
=> Shape kernels for 2D

.pre-commit-config.yaml, coxeter/families/data/MathematicaToPython.py, doc/source/development.rst, pyproject.toml
Updates the pre-commit configuration to perform more validation.
Simplifies development.
=> Update pre commit

README.rst, doc/source/examples.rst, doc/source/index.rst, doc/source/quickstart.rst
This PR adds a quickstart tutorial for new users of coxeter. It also adds more information about the purpose of coxeter and what use cases it addresses.
Closes #152, closes #153 
=> Add a tutorial some more general context to the README.

README.rst
Adds a badge for the new JOSS paper.
=> Add JOSS badge.

.circleci/config.yml
This PR removes the style checks step from CI.
With pre-commit.ci enabled, the style checks are redundant.
=> Remove the style check CI step

.circleci/config.yml, .pre-commit-config.yaml, setup.py
This PR enables code coverage with Codecov and updates the version of black used for style checks
The previous version of [black is broken by the release of Click 8.1.0](https://github.com/psf/black/issues/2964). Publishing and checking code coverage as part of CI is helpful.
=> Enable codecov and update black version

coxeter/families/common.py
=> Fixed #182

.pre-commit-config.yaml, ChangeLog.rst, coxeter/__init__.py, doc/source/conf.py, pyproject.toml, setup.cfg
=> Release v0.7.0

.circleci/config.yml
=> Fixed circleci wheel config

ChangeLog.rst
Changelog was incorrectly formatted due to missing header lines. This has been resolved. In addition, a misordered changelog subheader from the 0.7.0 release was fixed.
=> Fix headers in ChangeLog.rst

doc/environment.yml
=> Fix RTD using outdated furo template

.github/PULL_REQUEST_TEMPLATE.md, .github/dependabot.yml, .github/workflows/CI.yaml, .github/workflows/PublishPyPI.yaml, .github/workflows/update_pipfiles.yaml, doc/source/development.rst
~WIP: waiting on conda-forge update to 0.10.0 to actually rename the branch~
This brings `coxeter` in line with our other software and saves a (small) amount of dev time for each new PR. It's not a big deal either way, but I feel like we may as well
=> Rename master -> main
