glotzerlab/coxeter

coxeter/shape_families/plane_shape_families.py
Fix some issues with the documentation of the 523 shape family to clarify the nature of the constants S (the golden ratio) and s (its inverse).
Resolves #87 
=> Improve golden ratio documentation

Credits.rst, coxeter/shape_classes/circle.py, coxeter/shape_classes/convex_spheropolyhedron.py, tests/test_circle.py, tests/test_spheropolyhedron.py
added perimeter and circumference getter and setter tests and the ability to set the circumference and perimeter of a circle
simple, see summary
consistency between what we can get and set
=> added perimeter and circumference setters and tests

.circleci/config.yml, ChangeLog.rst, Credits.rst, coxeter/__doctest_fixtures.py, coxeter/shape_classes/circle.py, coxeter/shape_classes/convex_polygon.py, coxeter/shape_classes/convex_polyhedron.py, coxeter/shape_classes/convex_spheropolygon.py, coxeter/shape_classes/convex_spheropolyhedron.py, coxeter/shape_classes/ellipse.py, coxeter/shape_classes/ellipsoid.py, coxeter/shape_classes/polygon.py, coxeter/shape_classes/polyhedron.py, coxeter/shape_classes/sphere.py, coxeter/shape_families/__init__.py, coxeter/shape_families/common_families.py, coxeter/shape_families/plane_shape_families.py, setup.cfg
This PR enables doctests in pytest, so they will run during continuous integration.
To make doctests work, I enabled two options.
`ELLIPSIS` allows non-deterministic results to be ignored by putting `...`.
`NORMALIZE_WHITESPACE` allows lines to be wrapped for flake8 even if the output does not contain newlines.
I also reformatted the examples sections so they render better. Resolves #104.
Doctests ensure that the code examples continue to work as the package is changed.
=> Enable doctests

coxeter/shape_classes/ellipse.py, tests/test_ellipse.py
Adding getters and setters for the a and b parameters of an ellipsoid. 
See summary. 
There were no getter or setter checks for a and b. 
=> added getter and setters for a and b

coxeter/shape_classes/sphere.py, tests/test_sphere.py
added surface area setter and getter setter checks 
see summary
There was no surface area setter for the sphere
=> added surface area setter and getter setter checks 

coxeter/shape_classes/ellipsoid.py, tests/test_ellipsoid.py
Added getter and setter tests for the super-ellipsoid for a,b,c. 
Added getter and setter tests for the super-ellipsoid for a,b,c. 
There were no getter and setter tests for a,b,c. 
=> getter setter checks for a, b, c for a superellipsoid

ChangeLog.rst, Credits.rst, coxeter/families/shape_family.py, coxeter/shapes/convex_spheropolygon.py, tests/test_spheropolygon.py
This resolves a TODO item in the code by adding a setter method for spheropolygon area and perimeter.
=> Spheropolygon area setter

ChangeLog.rst, Credits.rst, coxeter/shapes/base_classes.py, coxeter/shapes/polygon.py, coxeter/shapes/polyhedron.py, coxeter/shapes/utils.py
Axis objects can be created automatically when plotting polygons / polyhedra.
Resolves TODO items. This copies some code that I wrote for freud.
=> Create axes for plotting if not provided.

tests/test_ellipse.py, tests/test_ellipsoid.py, tests/test_spheropolygon.py
Some tests weren't running because they were incorrectly named. @Tobias-Dwyer FYI, test functions have to start with the word `test_...`. I also fixed an issue with fixtures and `@given` (the argument order had to be swapped -- fixtures should go first and `@given` parameters go second).
=> Fix test names

setup.cfg
Coxeter isn't compatible with Python 2. Thus, we can't create a "universal" wheel. Instead, we need to use a Python 3 tag.
https://packaging.python.org/guides/distributing-packages-using-setuptools/#wheels
@vyasr You could consider deleting the previous wheel for 0.4.0 and re-generating a wheel with this fix. (Or you can decide that it doesn't matter.)
Fixes wheel compatibility.
=> Make a Python 3 wheel, not a universal wheel.

ChangeLog.rst, Credits.rst, coxeter/shapes/circle.py, coxeter/shapes/convex_spheropolygon.py, coxeter/shapes/convex_spheropolyhedron.py, coxeter/shapes/ellipse.py, coxeter/shapes/ellipsoid.py, coxeter/shapes/polygon.py, coxeter/shapes/polyhedron.py, coxeter/shapes/sphere.py, tests/test_ellipse.py, tests/test_ellipsoid.py
I made property setters look the same:
- Input parameter is named `value`.
- Property setting logic is always first (`if value > 0:`), error raising is always second (`else: raise`). This is my preference because it ensures the expected path is first (easier to read) and the condition matches the error message text (`if value > 0` matches the error `Value must be greater than zero.` and is thus easier to think through).
I also added setters for ellipse area and ellipsoid volume. (I specifically needed ellipsoid volume but wanted ellipse area to match.)
Resolves #114. I did not know the issue already existed and had been assigned to @Tobias-Dwyer, I just wanted to add the volume setter for ellipsoids and figured I'd improve the code base at the same time.
<sup>1</sup>The change breaks (or …
=> More consistent setters

coxeter/shapes/circle.py, coxeter/shapes/convex_polygon.py, coxeter/shapes/convex_polyhedron.py, coxeter/shapes/convex_spheropolygon.py, coxeter/shapes/convex_spheropolyhedron.py, coxeter/shapes/ellipse.py, coxeter/shapes/ellipsoid.py, coxeter/shapes/polygon.py, coxeter/shapes/polyhedron.py, coxeter/shapes/sphere.py
This PR uses public properties everywhere possible.
Public properties are validated when set and their names are shorter. All attributes that can be set should call the property setter in `__init__` instead of duplicating the validation logic in the constructor.
=> Use public properties everywhere.

ChangeLog.rst, tests/test_spheropolygon.py
This PR rewrites test that were implicitly reusing pytest fixtures to make this reuse explicit. I added a changelog entry since this may be important for others to track the reason for the failures.
#122 added various tests that reuse pytest fixtures in hypothesis tests. Those tests would pass with warnings in older versions of hypothesis, but the [recent release of hypothesis 6.0.0 makes this an error](https://hypothesis.readthedocs.io/en/latest/changes.html#v6-0-0). These changes will avoid problems in the future.
=> Rewrite tests to explicit reuse fixtures to avoid hypothesis errors.

coxeter/shapes/base_classes.py, coxeter/shapes/circle.py, coxeter/shapes/convex_spheropolygon.py, coxeter/shapes/convex_spheropolyhedron.py, coxeter/shapes/ellipse.py, coxeter/shapes/ellipsoid.py, coxeter/shapes/polygon.py, coxeter/shapes/polyhedron.py, coxeter/shapes/sphere.py, tests/test_ellipse.py, tests/test_ellipsoid.py, tests/test_polygon.py, tests/test_polyhedron.py, tests/test_spheropolyhedron.py
Use `_rescale` to change the length scale of all shapes. The method is implemented for each shape class, and allows for common logic for setters for properties like areas and volumes.
I also added several new property setters.
Simplifies implementations of property setters.
@Tobias-Dwyer Would you like to add tests to this PR? Tests are missing for the new setters. You can model them after similar property tests for other classes. After you've tested them, we can mark them off on the Feature Matrix document.
=> Add _rescale for use with setters.

ChangeLog.rst, coxeter/shapes/base_classes.py, coxeter/shapes/circle.py, coxeter/shapes/convex_spheropolygon.py, coxeter/shapes/convex_spheropolyhedron.py, coxeter/shapes/ellipse.py, coxeter/shapes/ellipsoid.py, coxeter/shapes/polygon.py, coxeter/shapes/polyhedron.py, coxeter/shapes/sphere.py, tests/test_spheropolygon.py, tests/test_spheropolyhedron.py
Removes `center`, `centroid`, and bounding circles/spheres from the spheropolygon and spheropolyhedron classes. The implementation of `centroid` was not valid for arbitrary sphero-shapes.
If it ain't broke, don't fix it. If it is broke, delete it before shipping. `#cantfixwontfix`
=> Remove center and bounding/bounded spheres/circles from sphero-shapes.

.gitignore, ChangeLog.rst, Credits.rst, coxeter/families/tabulated_shape_family.py, coxeter/shape_getters.py, coxeter/shapes/base_classes.py, coxeter/shapes/circle.py, coxeter/shapes/convex_polyhedron.py, coxeter/shapes/convex_spheropolygon.py, coxeter/shapes/convex_spheropolyhedron.py, coxeter/shapes/ellipse.py, coxeter/shapes/ellipsoid.py, coxeter/shapes/polygon.py, coxeter/shapes/polyhedron.py, coxeter/shapes/sphere.py, doc/source/conf.py, setup.py, tests/test_plato.py
[plato_scenes.pdf](https://github.com/glotzerlab/coxeter/files/5927311/plato_scenes.pdf)
Allows shapes to be displayed as [plato](https://plato-draw.readthedocs.io/en/latest/) scenes.
Most shapes are shown at `self.center`. Polygon-like shapes must be shown in a 2D scene, and thus must be rotated so that their normal is `[0, 0, 1]` and their center is the origin. Orientations are assumed to be `[1, 0, 0, 0]`. Colors are set to 50% gray.
Possible replacement for the `plot` method.
See the attached file for rendered examples!
@glotzerlab/coxeter-maintainers how do we want to test this? Add optional tests that function if plato is installed? If so, there is another issue that backends might still not be installed, so this is just hard to test on CI. In garnett, we have [a pretty hacky …
=> Add to_plato_scene feature.

.readthedocs.yaml
Removes LaTeX documentation formats to fix the build error shown here: https://readthedocs.org/projects/coxeter/builds/14275171/
```
Running Sphinx v4.1.1
loading translations [en]... done
making output directory... done
loading pickled environment... checking for /home/docs/checkouts/readthedocs.org/user_builds/coxeter/checkouts/latest/doc/source/coxeter.bib in bibtex cache... up to date
done
[autosummary] generating autosummary for: changelog.rst, coxeter.rst, credits.rst, development.rst, examples.rst, examples/DistanceToSurface.ipynb, examples/FormFactors.ipynb, examples/InertiaTensors.ipynb, examples/PointInShape.ipynb, examples/Spheres.ipynb, index.rst, license.rst, module-shape-getters.rst, package-families.rst, package-shapes.rst, quickstart.rst, zreferences.rst
building [mo]: …
```
=> Build only htmlzip docs.

.pre-commit-config.yaml, ChangeLog.rst, coxeter/families/plane_shape_families.py, coxeter/shapes/base_classes.py, coxeter/shapes/circle.py, coxeter/shapes/convex_spheropolygon.py, coxeter/shapes/convex_spheropolyhedron.py, coxeter/shapes/ellipse.py, coxeter/shapes/ellipsoid.py, coxeter/shapes/polygon.py, coxeter/shapes/sphere.py, tests/test_circle.py, tests/test_ellipse.py, tests/test_ellipsoid.py, tests/test_polygon.py, tests/test_polyhedron.py, tests/test_shape_families.py, tests/test_shape_getters.py, tests/test_sphere.py, tests/test_spheropolygon.py, tests/test_spheropolyhedron.py
Swap exact equality comparisons in tests with comparisons using `pytest.approx` or `numpy.testing.assert_allclose`.
Resolves #158.
=> Fix numerical precision in tests

.readthedocs.yaml
Dependency installs performed during the readthedocs build fail due to lack of memory. Switching to installs via mamba (rather than conda) should fix this error
=> Fix Readthedocs build error by switching dependency installs to mamba

tests/test_polyhedron.py, tests/test_spheropolygon.py, tests/test_spheropolyhedron.py
Until #179 is fixed, I added an `xfail` to the affected tests of bounding spheres for polyhedra. This ensures that library development is not stalled indefinitely due to a complex problem. See #179, #178 for details.
=> Expect failures due to numerical precision in miniball.

coxeter/families/common.py, doc/source/coxeter.bib
A few of the families defined in #177 have messy documentation that result from missing line breaks. This has been addressed, and the short docstrings (which display in the Classes table on readthedocs) have been made more uniform.
<sup>These changes fix a PR that I authored, so I have not modified the changelog.</sup>
=> Fixed documentation for common families

Credits.rst, coxeter/families/plane_shape_families.py, tests/test_shape_families.py
More tests were added and current tests were expanded for `test_shape_families.py`
Plane shape families can result in unexpected errors with parameter values close to transition points in shape space. More tests were added to cover this possibility, and integer values were replaced with "exact" floats to verify that transition point shapes can be generated. These tests confirm that the unexpected failures are a result of floating point precision, and not a deeper bug in the implementation. Also note that before #188 these functions return incorrect results rather than raising an error.
=> Improve shape family tests

tests/test_spheropolyhedron.py
Occasionally, the random rounding radius assigned to a convex spheropolyhedron in the `to_hoomd` test results in an invalid shape. This mainly happens with the many-faced catalan solids, where edge cylinders overlap in an unpredictable way. I have xfailed this test for now, but we should add some error checking to the ConvexSpheropolyhedron class to prevent undefined behavior.
=> xfail test_spheropolyhedron.py::to_hoomd

coxeter/shapes/polygon.py, tests/test_polygon.py
HOOMD expects an (N,2) array instead of the (N,3) representation coxeter uses for polygons. 
=> Fix to_hoomd for convex polygons

doc/source/_templates/page.html
Fix an issue where the x3dom code couldn't be loaded in the live/public version of the RTD build. This was caused by writing the url to the x3dom code with http instead of https. This issue is documented [here](https://stackoverflow.com/questions/18251128/why-am-i-suddenly-getting-a-blocked-loading-mixed-active-content-issue-in-fire) and you can verify it by clicking on the lock symbol in your status bar and clicking "disable protections for this site" - suddenly the models render properly!
I want docs to work plz thx
=> Switch HTTP to HTTPS protocol for script url in page template

ChangeLog.rst, coxeter/shapes/polygon.py, tests/test_polygon.py
Computing the edges and edge lengths of polygons is useful for testing shape moves and similar operations. This feature also brings the Polygon class more in line with new functionality in Polyhedron.
=> Add edge methods to Polygon and ConvexPolygon

coxeter/shapes/convex_polyhedron.py
Shape of input vertex arrays is now checked for ConvexPolyhedron, raising a ValueError (as in numpy) when the array is not (N,3)
Scipy convex hull would segfault if passed an array with more than two dimensions, leading to confusing behavior. This fix instead provides a nicely formatted error for users.
=> Add shape checking for ConvexPolyhedron
